#cloud-config

coreos:
  etcd:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new
    #discovery: http://10.0.0.9:4001/v2/keys/_etcd/registry/hillcluster 
    # multi-region and multi-cloud deployments need to use $public_ipv4
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
ssh_authorized_keys:
  # include one or more SSH public keys
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPanmcfyhfIcuqaJ99JumPd8HSf3HA9jqcrYRhskng8L9DA8RzRsYF9f+1tJPp28aiUHzZ4wEeUBTjvpgViGcdfEoTMnCkIdq23wNhXn+eWcz4IyxnnK7QsID8GvPkonLa5JtVB1j8BS1zeJU0bfK0i+yB+WITIt7tq2yZnSeSuwYSoQEMSfgMD7+x660fYs7dCgWhaWK44/K86mLkj0TMDWj5O1StFJWp8t/+/6LnTqnl3KQcl5Cn2e7R3RNomPFhOehwPzWjUgwSulD9PHOSZv3UoNfWT6pdpLivKw4nUfSrFkleCKUYcfhz+svUJXNO/6VoTUzZy4Dz50aNjYqi hill@hillopen
